ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

RUN  DEBIAN_FRONTEND=noninteractive apt-get update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
				    postgresql-client

##
## Geopython, XML
##
RUN	mamba install -c conda-forge  \
	conda-forge::gdal conda-forge:libgdal \
	conda-forge::lxml conda-forge:libiconv conda-forge::geopandas conda-forge::geoplot \
	conda-forge::folium conda-forge::pysal conda-forge::esda conda-forge::rasterio conda-forge::poppler \
	conda-forge::psycopg2 conda-forge::mysqlclient conda-forge::ipython-sql && \
	mamba clean -afy && \
	DEBIAN_FRONTEND=noninteractive apt-get update && \	
	DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
				       	        xqilla libxqilla-dev && \
	rm -rf /var/lib/apt/lists/* && \
	$CONDA_DIR/bin/pip install contextily libpysal mgwr mapclassify esda python-simplexquery pymysql

# Install mongosh
ADD https://downloads.mongodb.com/compass/mongosh-2.2.12-linux-x64.tgz /tmp

RUN cd /tmp && tar zxf mongosh-2.2.12-linux-x64.tgz && cp /tmp/mongosh-2.2.12-linux-x64/bin/mongosh /usr/local/bin && cp /tmp/mongosh-2.2.12-linux-x64/bin/mongosh_crypt_v1.so /usr/local/lib && rm -rf /tmp/mongosh-2.2.12-linux-x64*

# Install MongoDB database Tools
ADD https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.5.tgz /tmp
RUN cd /tmp && tar zxf mongodb-database-tools-ubuntu2204-x86_64-100.9.5.tgz && cp mongodb-database-tools-ubuntu2204-x86_64-100.9.5/bin/* /usr/local/bin && rm -rf mongodb-database-tools-ubuntu2204-x86_64-100.9.5*

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
