ARG BASE_CONTAINER=define_as_build_arg
FROM ${BASE_CONTAINER}
LABEL MAINTAINER="CSEL Ops <cs-ops@colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

#Dockerfile for CSCI3022 , DataScience Algorithm
# Install otter-grader
RUN python3 -m pip install \ 
      otter-grader==5.1.3 pdfkit PyPDF2 plotly \
	jupysql==0.8.0 \
	matplotlib==3.7.1 \
	mdit-py-plugins==0.4.0 \
	numpy==1.24.2 \
	pandas==2.0.2 \
	plotly==5.13.1 \
	requests==2.28.2 \
	scikit-image==0.19.3 \
	scikit-learn==1.2.2 \
	scipy==1.10.1 \
	seaborn==0.12.2 \
	statsmodels==0.14.0 \
	sqlalchemy==2.0.16 \
	ipywidgets==8.0.7 \
	folium==0.14.0 \
        numba==0.57.1

# Install R packages for otter-grader
#RUN R -e "devtools::install_github('ucbds-infra/ottr@stable')"

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
