ARG BASE_CONTAINER=gcr.io/emerald-agility-749/notebook:v1.0.75
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

##
## Perf, MPICH
## You need to enable CAP_SYS_ADMIN to use perf in Docker
## For more infomration, refer to https://blog.alicegoldfuss.com/enabling-perf-in-kubernetes/
RUN  DEBIAN_FRONTEND=noninteractive apt-get update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
     				    linux-tools-generic mpich libmpich-dev hwloc  && \
     cd /usr/lib/linux-tools && \
     find `pwd` -name perf | xargs -I org_perf ln -s org_perf /usr/local/bin/perf && \
     rm -rf /var/lib/apt/lists/*

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan && \
        rm -rf /usr/local/bin/fix-permissions

USER    $NB_UID