ARG BASE_CONTAINER=define_as_build_arg
FROM ${BASE_CONTAINER}
LABEL MAINTAINER="CSEL Ops <cs-ops@colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

#Dockerfile for CSCI3022 , DataScience Algorithm
# Install otter-grader
RUN python3 -m pip install otter-grader==4.4.1 pdfkit PyPDF2 plotly

# Install R packages for otter-grader
#RUN R -e "devtools::install_github('ucbds-infra/ottr@stable')"

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
