ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root
ENV DEBIAN_FRONTEND noninteractive

# GREQ0380353 Install shared packages ECEN 1310 / ECEN 4313
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
 && apt-get install -yq bc libjemalloc2 libjemalloc-dev --no-install-recommends \
 && apt-get clean

# Remove jupyter kernel
RUN     echo "y" | /opt/conda/bin/jupyter-kernelspec remove -y \
        ir julia-1.7 # xcpp17 

# Remove drawio
RUN pip uninstall -y jupyterlab-drawio

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
