ARG BASE_CONTAINER=define_as_build_arg
#
# From https://github.com/almond-sh/almond
#
FROM $BASE_CONTAINER as coursier_base
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

ARG   LOCAL_IVY=no

USER root

RUN apt-get -y update && \
    apt-get install --no-install-recommends -y \
      curl \
      ca-certificates-java && \
    apt-get clean && \
#
# from https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html
#
    apt-get update &&\
    apt-get install apt-transport-https curl gnupg -yqq && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import && \
    chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg && \
    apt-get update && \
    apt-get install sbt && \
    rm -rf /var/lib/apt/lists/*

RUN curl -Lo /usr/local/bin/coursier https://github.com/coursier/coursier/releases/download/v2.0.0-RC3-2/coursier && \
    chmod +x /usr/local/bin/coursier

USER $NB_UID

# ensure the JAR of the CLI is in the coursier cache, in the image
RUN /usr/local/bin/coursier --help

ARG ALMOND_VERSION
# Set to a single Scala version string or list of Scala versions separated by a space.
# i.e SCALA_VERSIONS="2.12.9 2.13.0"
ARG SCALA_VERSIONS
COPY scripts/pl-install-kernels.sh .

USER root
RUN   sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.5.2/2.13-2.5.2) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'

RUN 	./pl-install-kernels.sh && \
	rm pl-install-kernels.sh && \
	rm -rf .ivy2 && \
	ipython kernelspec list
	
RUN     ls -lR /home/jovyan && \
	rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID