ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

##
## Perf, MPICH
## You need to enable CAP_SYS_ADMIN to use perf in Docker
## For more infomration, refer to https://blog.alicegoldfuss.com/enabling-perf-in-kubernetes/
RUN apt-get update && \
    apt-get -y install curl f2c && \
    rm -rf /var/lib/apt/lists/*

RUN curl -o /tmp/tisean-3.0.1-2_amd64.deb https://foundation.cs.colorado.edu/juypterhub/tisean_3.0.1-2_amd64.deb && \
    dpkg -i /tmp/tisean-3.0.1-2_amd64.deb && \
    rm /tmp/tisean-3.0.1_amd64.deb \

RUN rm -rf /home/jovyan && \
    mkdir /home/jovyan && \
    chown $NB_UID:$NB_GID /home/jovyan

USER $NB_UID
