ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER    root

ENV     DEBIAN_FRONTEND noninteractive

RUN     DEBIAN_FRONTEND=noninteractive apt-get update && \
                                       rm -rf /var/lib/apt/lists/* && \
                                       pip3 install tensorflow && \
                                       git clone https://github.com/rasbt/python-machine-learning-book-3rd-edition /opt/python-machine-learning-book-3rd-edition && \
                                       chown $NB_UID:$NB_GID /opt/python-machine-learning-book-3rd-edition

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
