ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root
ENV DEBIAN_FRONTEND noninteractive

#ECEN 4553 Compilter Construction
# Install PLY(Python Lex-Yacc)
RUN cd /tmp && git clone https://github.com/dabeaz/ply.git && cd ply && python install.py && \
     rm -rf /tmp/ply

# Install pytest
RUN pip install pytest

# Remove jupyter kernel
RUN     echo "y" | /opt/conda/bin/jupyter-kernelspec remove -y \
        ir julia-1.6 # xcpp17 

# Remove drawio
RUN pip uninstall -y jupyterlab-drawio

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
