ARG BASE_CONTAINER=define_as_build_arg
FROM ${BASE_CONTAINER}
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

#
# Dockefile for CSCI 3090 : Quantum Computing
#               ECEN 4925 : Quantum Hardware
#
RUN pip install pytest cvxpy qutip qiskit networkx noisyopt qiskit-ibm-runtime

# Install qiskit-textbook for additional qiskit helpers
RUN pip install git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src

# Install package for nice matplotlib circuit drawing
RUN pip install pylatexenc

# The current version is old and causing errors
RUN pip install --upgrade matplotlib


RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
