ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

##
## Perf, MPICH
## You need to enable CAP_SYS_ADMIN to use perf in Docker
## For more infomration, refer to https://blog.alicegoldfuss.com/enabling-perf-in-kubernetes/
RUN apt-get update && \
    apt-get -y install wget && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://www.pks.mpg.de/~tisean/TISEAN_3.0.1.tar.gz -P /tmp && \
    tar xf /tmp/TISEAN_3.0.1.tar.gz -C /tmp/ && \
    cd /tmp/Tisean_3.0.1/ && ./configure --prefix=/usr/local/ && make && make install && \
    rm -rf /tmp/Tisean_3.0.1 /tmp/TISEAN_3.0.1.tar.gz

RUN rm -rf /home/jovyan && \
    mkdir /home/jovyan && \
    chown $NB_UID:$NB_GID /home/jovyan

USER $NB_UID
