ARG BASE_CONTAINER=gcr.io/emerald-agility-749/notebook:v1.0.75
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root

ENV DEBIAN_FRONTEND noninteractive

#
# Add material for AI classes
#

RUN	$CONDA_DIR/bin/pip install bqplot ipythonblocks tensorflow qpsolvers \
			   quadprog opencv-python keras Image jp_proxy_widget \
			   git+https://github.com/aaronwatters/jp_doodle && \
	jupyter labextension install  --no-build bqplot && \
	jupyter nbextension enable --py --sys-prefix jp_proxy_widget && \
	jupyter labextension install  --no-build jp_proxy_widget

##
## Build jupyter lab extensions
##
RUN	jupyter lab build

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan && \
        rm -rf /usr/local/bin/fix-permissions

USER    $NB_UID