ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="CSEL Ops <admin@cs.colorado.edu>"

USER root
ENV DEBIAN_FRONTEND noninteractive

# Remove jupyter kernel
RUN     echo "y" | /opt/conda/bin/jupyter-kernelspec remove -y python3 ir julia-1.8

# Remove 
RUN pip uninstall -y jupyterlab-drawio jupyter-codeserver-proxy  jupyterlab-latex

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
